apiVersion: apps/v1
kind: Deployment
metadata:
    name: task-processor
spec:
    replicas: 3
    selector:
        matchLabels:
            app: task-processor
    template:
        metadata:
            labels:
                app: task-processor
        spec:
            containers:
                -   name: task-processor
                    image: registry/task-processor:latest
                    ports:
                        -   containerPort: 8080
                    resources:
                        requests:
                            memory: "512Mi"
                            cpu: "500m"
                        limits:
                            memory: "1Gi"
                            cpu: "1000m"
                    env:
                        -   name: SPRING_PROFILES_ACTIVE
                            value: "production"